language: java
jdk:
  - oraclejdk8

install: ant

dist: trusty

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -minera.jose.luis@gmail.com
on_failure: always
